-- Promo codes table
create table if not exists promo_codes (
  id bigint generated by default as identity primary key,
  code text unique not null,
  discount_percent numeric not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table promo_codes enable row level security;

-- Allow anyone to read active promo codes (for storefront validation)
create policy "Public can read promo codes" on promo_codes
  for select using (true);

-- Allow authenticated (admin) users full access
create policy "Authenticated full access promo codes" on promo_codes
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- Products: multiple images
alter table products add column if not exists images jsonb not null default '[]'::jsonb;

-- Settings: maintenance mode (stored as a row in the settings table)
insert into settings (key, value)
values ('maintenance_mode', 'false'::jsonb)
on conflict (key) do nothing;
